version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
  port: 4502
validators:
- name: alice
  bonded: 100000000stake
  config:
    consensus:
      create_empty_blocks: false
      create_empty_blocks_interval: "2s"
    rpc:
      laddr: "tcp://0.0.0.0:26661"
